set(TOS_SANITIZER "none" CACHE STRING "Validation instrumentation: none, address-undefined, thread")
set_property(CACHE TOS_SANITIZER PROPERTY STRINGS none address-undefined thread)
if(NOT TOS_SANITIZER MATCHES "^(none|address-undefined|thread)$")
    message(FATAL_ERROR "Invalid TOS_SANITIZER: ${TOS_SANITIZER}")
endif()

function(tos_check_sanitizer support_variable flag)
    include(CheckCXXSourceCompiles)
    include(CMakePushCheckState)
    cmake_push_check_state(RESET)
    # A parent's cross-compile checks may build static archives; validate linking as well.
    set(CMAKE_TRY_COMPILE_TARGET_TYPE EXECUTABLE)
    set(CMAKE_REQUIRED_FLAGS "${flag}")
    set(CMAKE_REQUIRED_LINK_OPTIONS "${flag}")
    check_cxx_source_compiles("int main() { return 0; }" ${support_variable})
    cmake_pop_check_state()
endfunction()

set(TOS_TEST_TIMEOUT 30)
if(NOT TOS_SANITIZER STREQUAL "none")
    if(WIN32 OR NOT CMAKE_SYSTEM_NAME MATCHES "^(Linux|Darwin)$" OR
       NOT CMAKE_CXX_COMPILER_ID MATCHES "^(GNU|Clang|AppleClang)$")
        message(FATAL_ERROR "TOS_SANITIZER requires GCC/Clang on Linux or macOS")
    endif()
    if(TOS_INSTALL)
        message(FATAL_ERROR "Sanitizer validation builds require TOS_INSTALL=OFF")
    endif()
    if(TOS_SANITIZER STREQUAL "address-undefined")
        set(TOS_SANITIZER_FLAG -fsanitize=address,undefined)
    else()
        set(TOS_SANITIZER_FLAG -fsanitize=thread)
    endif()
    # Test the compiler and linker together without mutating the parent's flags.
    string(MAKE_C_IDENTIFIER "TOS_SUPPORTS_${TOS_SANITIZER}" support_variable)
    tos_check_sanitizer(${support_variable} "${TOS_SANITIZER_FLAG}")
    if(NOT ${support_variable})
        message(FATAL_ERROR "Compiler cannot compile/link TOS_SANITIZER=${TOS_SANITIZER}")
    endif()
    set(TOS_TEST_TIMEOUT 120)
endif()

function(tos_instrument_target target)
    if(TOS_SANITIZER STREQUAL "none")
        return()
    endif()
    target_compile_options(${target} PRIVATE
        ${TOS_SANITIZER_FLAG} -g -O1 -fno-omit-frame-pointer -fno-sanitize-recover=all)
    target_link_options(${target} PRIVATE ${TOS_SANITIZER_FLAG})
    get_target_property(target_type ${target} TYPE)
    if(target_type STREQUAL "STATIC_LIBRARY")
        # Source consumers need the runtime; installed Release packages remain unaffected.
        target_link_options(${target} INTERFACE "$<BUILD_INTERFACE:${TOS_SANITIZER_FLAG}>")
    endif()
endfunction()
